# Generated by Django 4.2.13 on 2024-06-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='DataCriacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='DataFinalizada',
            new_name='data_entrega',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='Entrega',
        ),
        migrations.AddField(
            model_name='todos',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todos',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
    ]
