# Generated by Django 5.0.6 on 2024-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0002_rename_datacriacao_todos_data_criacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='titulo',
            new_name='tarefa',
        ),
    ]
